#ifndef _CONFIG_H_
#define _CONFIG_H_

#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10
#define PHIX_TOTAL_INTERRUPTS 512

/* 100MB heap size */
#define PHIX_HEAP_SIZE_BYTES (100 * 1024 * 1024)
#define PHIX_HEAP_BLOCK_SIZE 4096
#define PHIX_HEAP_SADDRESS 0x01000000
#define PHIX_HEAP_TABLE_ADDRESS 0x00007E00

#define PHIX_SECTOR_SIZE 512

#define PHIX_MAX_PATH 108

#define PHIX_MAX_FILESYSTEMS 12
#define PHIX_MAX_FILE_DESCRIPTORS 512

#define PHIX_TOTAL_GDT_SEGMENTS 6

#define PHIX_PROGRAM_VIRTUAL_ADDRESS 0x400000
#define PHIX_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3FF000
#define PHIX_USER_PROGRAM_STACK_SIZE (16 * 1024)
#define PHIX_PROGRAM_VIRTUAL_STACK_ADDRESS_END                                                     \
    (PHIX_PROGRAM_VIRTUAL_STACK_ADDRESS_START - PHIX_USER_PROGRAM_STACK_SIZE)

#define PHIX_MAX_PROGRAM_ALLOCATIONS 1024
#define PHIX_MAX_PROGRAM_FILE_DESCRIPTORS 1
#define PHIX_MAX_PROCESSES 12
#define USER_DATA_SEGMENT 0x23
#define USER_CODE_SEGMENT 0x1B

#define PHIX_MAX_SYSCALLS 1024

#define PHIX_KEYBOARD_BUFFER_SIZE 1024

#endif /* _CONFIG_H */
