[unstable]
# cross compile core library for custom target
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
extra-link-arg = true

[build]
target = "i686-unknown-none.json"

[target.i686-unknown-none]
rustflags = "--emit=obj -O"

